### PR TITLE
Update diagram to use mermaid syntax

### PR DESCRIPTION
**Pull request by rebekaburnett**

### CODE REVIEW

**Comment by rebekaburnett** [comment]
login
Please check how it looks in this attached image.

**Comment by cloveras** [comment]
Shouln't there be some kind of activity after the initial POST request..?

**Comment by rebekaburnett** [comment]
> Shouldn't there be some kind of activity after the initial POST request..? Also in the original diagram.

It's a question for the login team.

**Comment by jonkjenn** [comment]
> Shouldn't there be some kind of activity after the initial POST request..? Also in the original diagram.

I don't think it was intended to contain everything in detail. Wanted to keep it simple. If this detail level is the most helpful I don't know.

**Review by jonkjenn — APPROVED** [review]

**Pull request merged**
