### PR TITLE
Add postman collection for ciba

### PR DESCRIPTION
**Pull request by thormarius**

### CODE REVIEW

**Comment by rebekaburnett** [comment]
@thormarius This is looking good! Thanks for doing it! I didn't get around to it yet, obvs. :-)

**Comment by thormarius** [comment]
@rebekaburnett this one is ready for review now - would appreciate if you could try out the ciba collection and give feedback on how it works for you

**Comment by cloveras** [comment]
@rebekaburnett @thormarius Can this Postman collection be included in the main collection for Login? I would like all APIs to have just one Postman collection, not multiple.

**Comment by rebekaburnett** [comment]
> @rebekaburnett @thormarius Can this Postman collection be included in the main collection for Login? I would like all APIs to have just one Postman collection, not multiple.

Yes, that should be possible. I can do that, if it's ok with you, @thormarius

**Comment by thormarius** [comment]
> @rebekaburnett @thormarius Can this Postman collection be included in the main collection for Login? I would like all APIs to have just one Postman collection, not multiple.
Technically it can, personally I think that's a bit messy and from experience the audience for these two flows are quite different. I'll leave it to you to make the decision, I'm really ok with both.

**Comment by thormarius** [comment]
> Yes, that should be possible. I can do that, if it's ok with you, @thormarius

Yep, go for it if you prefer to merge it

**Review by rebekaburnett — APPROVED** [review]

**Pull request merged**
